services:
  database:
    container_name: my_mongo
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ADMIN}
      - MONGO_INITDB_DATABASE=auth
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ADMIN_PASS}
    networks: 
      - mongo-compose-network
    ports:
      - '27017:27017'
    volumes:
        - type: volume
          source: mongodb_data_volume
          target: /data/db

  mongoexpress:
    container_name: mongo-express
    image: mongo-express:0.54
    depends_on:
      - database
    networks: 
      - mongo-compose-network
    environment:
      - ME_CONFIG_MONGODB_SERVER=my_mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ADMIN}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ADMIN_PASS}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_ADMIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_ADMIN_PASS}
    ports:
      - '8081:8081' 

  setupmongo:
    container_name : addcollection
    image : addcollection:1.0.0
    depends_on:
      database : 
        condition : service_started
    networks : 
      - mongo-compose-network
    env_file : 
      .env

  fastapi:
    container_name : jmfastapi
    image : jmfastapi:1.0.0
    depends_on:
      setupmongo:
        condition : service_completed_successfully
    networks : 
      - mongo-compose-network
    env_file : 
      .env
    ports:
      - '8000:8000'


networks:
  mongo-compose-network:

volumes:
      mongodb_data_volume:
        # external: true